const canvas=document.getElementById("gameCanvas"),ctx=canvas.getContext("2d");const TILE=32,SAVE_KEY="cityBuilder1";const costs={road:50,power:5000,water:4000,residential:500,commercial:800,industrial:1000},capacities={residential:12,commercial:2,industrial:4},jobs={commercial:4,industrial:8},powerPerPlant=250,waterPerPlant=250,income={residential:2,commercial:18,industrial:25},expense={residential:1,commercial:5,industrial:10};let money=50000,population=0,year=1,month=1,selectedTool="select",grid={},zoom=1,offsetX=0,offsetY=0,dragging=false,panning=false,lastMouseX=0,lastMouseY=0,touches=new Map(),pinchStartDistance=null,pinchStartZoom=1;
const moneyEl=document.getElementById("money"),populationEl=document.getElementById("population"),dateEl=document.getElementById("date"),housingEl=document.getElementById("housing"),commercialEl=document.getElementById("commercial"),industrialEl=document.getElementById("industrial"),powerEl=document.getElementById("power"),waterEl=document.getElementById("water"),jobsEl=document.getElementById("jobs"),balanceEl=document.getElementById("balance"),demandResidentialEl=document.getElementById("demandResidential"),demandCommercialEl=document.getElementById("demandCommercial"),demandIndustrialEl=document.getElementById("demandIndustrial"),warningEl=document.getElementById("warning"),messageEl=document.getElementById("message");
function resizeCanvas(){const r=canvas.getBoundingClientRect(),d=window.devicePixelRatio||1;canvas.width=Math.floor(r.width*d);canvas.height=Math.floor(r.height*d);ctx.setTransform(d,0,0,d,0,0);draw()}window.addEventListener("resize",resizeCanvas);function key(x,y){return`${x},${y}`}function getTile(x,y){return grid[key(x,y)]||null}function setTile(x,y,type){grid[key(x,y)]={type,level:.5}}function deleteTile(x,y){delete grid[key(x,y)]}
function screenToWorld(sx,sy){const r=canvas.getBoundingClientRect();return{x:Math.floor((sx-r.left-offsetX)/zoom/TILE),y:Math.floor((sy-r.top-offsetY)/zoom/TILE)}}function worldToScreen(x,y){return{x:x*TILE*zoom+offsetX,y:y*TILE*zoom+offsetY}}
function isRoadConnected(x,y){return getTile(x+1,y)?.type==="road"||getTile(x-1,y)?.type==="road"||getTile(x,y+1)?.type==="road"||getTile(x,y-1)?.type==="road"}
function buildAt(x,y,tool,silent=false){const existing=getTile(x,y);if(tool==="select")return false;if(tool==="bulldoze"){if(existing){deleteTile(x,y);updateUI();return true}return false}if(existing)return false;const isZone=tool==="residential"||tool==="commercial"||tool==="industrial";if(isZone&&!isRoadConnected(x,y)){if(!silent)setMessage("Gebiete müssen direkt an einer Straße liegen!");return false}if(money<costs[tool]){if(!silent)setMessage("Nicht genug Geld!");return false}money-=costs[tool];setTile(x,y,tool);updateUI();return true}
function countType(type){return Object.values(grid).filter(t=>t.type===type).length}
function calculateInfrastructure(){let pc=countType("power")*powerPerPlant,wc=countType("water")*waterPerPlant,pd=0,wd=0;for(const t of Object.values(grid)){if(t.type==="residential"){pd++;wd++}else if(t.type==="commercial"){pd+=2;wd+=2}else if(t.type==="industrial"){pd+=4;wd+=4}}return{powerCapacity:pc,waterCapacity:wc,powerDemand:pd,waterDemand:wd}}
function calculatePopulation(){const i=calculateInfrastructure(),okP=i.powerDemand<=i.powerCapacity,okW=i.waterDemand<=i.waterCapacity;let p=0;for(const[k,t]of Object.entries(grid)){if(t.type!=="residential")continue;const[x,y]=k.split(",").map(Number);if(isRoadConnected(x,y))p+=capacities.residential}population=(!okP||!okW)?Math.floor(p*.25):p}
function calculateJobs(){let t=0;for(const z of Object.values(grid))if(jobs[z.type])t+=jobs[z.type];return t}function calculateBalance(){let t=0;for(const z of Object.values(grid)){if(income[z.type])t+=income[z.type];if(expense[z.type])t-=expense[z.type]}return t}
function calculateDemand(){return{residential:Math.max(0,Math.min(100,60-countType("residential")*4+Math.max(0,population/10))),commercial:Math.max(0,Math.min(100,50+population/2-countType("commercial")*8)),industrial:Math.max(0,Math.min(100,45+population/3-countType("industrial")*7))}}
function updateUI(){calculatePopulation();const i=calculateInfrastructure(),j=calculateJobs(),b=calculateBalance(),d=calculateDemand();moneyEl.textContent=`${Math.floor(money).toLocaleString("de-DE")} €`;populationEl.textContent=population.toLocaleString("de-DE");dateEl.textContent=`Jahr ${year} – Monat ${month}`;housingEl.textContent=countType("residential");commercialEl.textContent=countType("commercial");industrialEl.textContent=countType("industrial");powerEl.textContent=`${i.powerDemand} / ${i.powerCapacity}`;waterEl.textContent=`${i.waterDemand} / ${i.waterCapacity}`;jobsEl.textContent=j;balanceEl.textContent=`${b>=0?"+":""}${b.toLocaleString("de-DE")} €`;demandResidentialEl.style.width=`${d.residential}%`;demandCommercialEl.style.width=`${d.commercial}%`;demandIndustrialEl.style.width=`${d.industrial}%`;const w=[];if(i.powerDemand>i.powerCapacity)w.push("⚡ Zu wenig Strom");if(i.waterDemand>i.waterCapacity)w.push("💧 Zu wenig Wasser");warningEl.textContent=w.join(" · ");warningEl.classList.toggle("hidden",!w.length);draw()}
function setMessage(text){messageEl.textContent=text;clearTimeout(setMessage.timeout);setMessage.timeout=setTimeout(()=>messageEl.textContent="",2500)}
function drawGrid(){const r=canvas.getBoundingClientRect();ctx.save();ctx.translate(offsetX,offsetY);ctx.scale(zoom,zoom);const sx=Math.floor((-offsetX/zoom)/TILE)-1,ex=Math.ceil((r.width-offsetX)/zoom/TILE)+1,sy=Math.floor((-offsetY/zoom)/TILE)-1,ey=Math.ceil((r.height-offsetY)/zoom/TILE)+1;ctx.strokeStyle="#263244";ctx.lineWidth=1/zoom;for(let x=sx;x<=ex;x++){ctx.beginPath();ctx.moveTo(x*TILE,sy*TILE);ctx.lineTo(x*TILE,ey*TILE);ctx.stroke()}for(let y=sy;y<=ey;y++){ctx.beginPath();ctx.moveTo(sx*TILE,y*TILE);ctx.lineTo(ex*TILE,y*TILE);ctx.stroke()}ctx.restore()}
function drawTile(x,y,t){const p=worldToScreen(x,y),s=TILE*zoom,c={road:"#4b5563",power:"#f59e0b",water:"#3b82f6",residential:"#22c55e",commercial:"#a855f7",industrial:"#f97316"},icons={road:"▰",power:"⚡",water:"💧",residential:"🏠",commercial:"🏪",industrial:"🏭"};ctx.fillStyle=c[t.type]||"#6b7280";ctx.fillRect(p.x+1,p.y+1,s-2,s-2);ctx.textAlign="center";ctx.textBaseline="middle";ctx.font=`${Math.max(10,s*.5)}px Arial`;ctx.fillStyle="#fff";ctx.fillText(icons[t.type]||"",p.x+s/2,p.y+s/2);if(["residential","commercial","industrial"].includes(t.type)){const w=s*.75,h=Math.max(2,s*.07);ctx.fillStyle="#111827";ctx.fillRect(p.x+(s-w)/2,p.y+s-h-3,w,h);ctx.fillStyle="#fff";ctx.fillRect(p.x+(s-w)/2,p.y+s-h-3,w*t.level,h)}}
function draw(){const r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);drawGrid();for(const[k,t]of Object.entries(grid)){const[x,y]=k.split(",").map(Number);drawTile(x,y,t)}}
function setTool(tool){selectedTool=tool;document.querySelectorAll(".tool").forEach(b=>b.classList.toggle("active",b.dataset.tool===tool));setMessage(tool==="bulldoze"?"Abriss ausgewählt.":`Werkzeug: ${tool}`)}
document.querySelectorAll(".tool").forEach(b=>b.addEventListener("click",()=>setTool(b.dataset.tool)));
canvas.addEventListener("contextmenu",e=>{e.preventDefault();const p=screenToWorld(e.clientX,e.clientY);buildAt(p.x,p.y,"bulldoze")});
canvas.addEventListener("mousedown",e=>{lastMouseX=e.clientX;lastMouseY=e.clientY;if(e.button===1){panning=true;return}if(e.button===0){dragging=true;const p=screenToWorld(e.clientX,e.clientY);if(selectedTool!=="select")buildAt(p.x,p.y,selectedTool)}});
window.addEventListener("mousemove",e=>{const dx=e.clientX-lastMouseX,dy=e.clientY-lastMouseY;if(panning){offsetX+=dx;offsetY+=dy;draw()}else if(dragging&&selectedTool!=="select"&&selectedTool!=="bulldoze"){const p=screenToWorld(e.clientX,e.clientY);buildAt(p.x,p.y,selectedTool,true)}lastMouseX=e.clientX;lastMouseY=e.clientY});window.addEventListener("mouseup",()=>{dragging=false;panning=false});
canvas.addEventListener("wheel",e=>{e.preventDefault();const oz=zoom,r=canvas.getBoundingClientRect(),wx=(e.clientX-r.left-offsetX)/oz,wy=(e.clientY-r.top-offsetY)/oz;zoom*=e.deltaY<0?1.1:.9;zoom=Math.max(.35,Math.min(3,zoom));offsetX=e.clientX-r.left-wx*zoom;offsetY=e.clientY-r.top-wy*zoom;draw()},{passive:false});
canvas.addEventListener("touchstart",e=>{for(const t of e.changedTouches)touches.set(t.identifier,{x:t.clientX,y:t.clientY});if(touches.size===1){const t=[...touches.values()][0];lastMouseX=t.x;lastMouseY=t.y}if(touches.size===2){pinchStartDistance=getTouchDistance();pinchStartZoom=zoom}});
canvas.addEventListener("touchmove",e=>{e.preventDefault();for(const t of e.changedTouches)touches.set(t.identifier,{x:t.clientX,y:t.clientY});if(touches.size===1){const t=[...touches.values()][0];offsetX+=t.x-lastMouseX;offsetY+=t.y-lastMouseY;lastMouseX=t.x;lastMouseY=t.y;draw()}if(touches.size===2&&pinchStartDistance){zoom=pinchStartZoom*(getTouchDistance()/pinchStartDistance);zoom=Math.max(.35,Math.min(3,zoom));draw()}},{passive:false});
canvas.addEventListener("touchend",e=>{for(const t of e.changedTouches)touches.delete(t.identifier);if(touches.size<2)pinchStartDistance=null});canvas.addEventListener("touchcancel",e=>{for(const t of e.changedTouches)touches.delete(t.identifier);pinchStartDistance=null});function getTouchDistance(){const v=[...touches.values()];return v.length<2?0:Math.hypot(v[0].x-v[1].x,v[0].y-v[1].y)}
function saveGame(){localStorage.setItem(SAVE_KEY,JSON.stringify({money,population,year,month,grid,zoom,offsetX,offsetY}));setMessage("Spiel gespeichert.")}
function loadGame(){let raw=localStorage.getItem(SAVE_KEY)||localStorage.getItem("cityBuilder3");if(!raw)return;try{const d=JSON.parse(raw);money=d.money??money;population=d.population??population;year=d.year??year;month=d.month??month;grid=d.grid??grid;zoom=d.zoom??zoom;offsetX=d.offsetX??offsetX;offsetY=d.offsetY??offsetY;setMessage("Spielstand geladen.")}catch{setMessage("Spielstand konnte nicht geladen werden.")}}
function advanceMonth(){money+=calculateBalance();month++;if(month>12){month=1;year++}updateUI();saveGame()}
loadGame();resizeCanvas();updateUI();setInterval(advanceMonth,20000);
